### PR TITLE
feat(frontend): add profile dropdown

### LINKED ISSUE #49: Add profile dropdown to navbar
Basically, two features:
- account name (name surname + student index number)
- logout button

### LINKED ISSUE #50: Change index page behavior
Now index page is empty but login info and logout button (to move in #49).

Index should has some information - as news page (so what we should do with current news page?)

### PR DESCRIPTION
**Pull request by Rei-x**
Closes #50

Closes #49

### CODE REVIEW

**Review by Omikorin — CHANGES_REQUESTED** [review]
Taken using desktop mode on Chrome. Check if there are some placement/margins problem. Photo should be in the right of edge of navbar

**Comment by Rei-x** [comment]
what do you mean, more on the right?

**Review by Omikorin — APPROVED** [review]

**Pull request merged**
